name: drivex
services:
  drivex-api:
    image: drivex.api
    build:
      context: .
      dockerfile: DriveX.API/Dockerfile
    depends_on:
      - drivex-db

  drivex-db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: drivex-db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - drivex-net
    restart: on-failure:3
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "drivex-db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4GB
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    networks:
      - drivex-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  pgadmin-data:
  pg-data:

networks:
  drivex-net:
    driver: bridge
